version: "3"
services:
  oauth-client:
    container_name: oauth-client
    restart: always
    volumes:
      - ./download:/src/download
      - ./.data:/src/.data
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    labels:
      - traefik.http.routers.oauth-client.rule=Host(`time-track.westwerk.ac`)
      - traefik.http.routers.oauth-client.entrypoints=websecure,web
      - traefik.http.routers.oauth-client.service=oauth-client
      - traefik.http.services.oauth-client.loadbalancer.server.port=3000
      - traefik.http.routers.oauth-client.tls=true
      - traefik.http.routers.oauth-client.tls.certresolver=myresolver
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true
  reverse-proxy:
    image: traefik:v2.10
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./acme.json:/acme.json
    labels:
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true
